# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build ungc
  timeoutInMinutes: 360
  steps:
  - checkout: self
    submodules: true
  - powershell: git checkout --recurse-submodules 85.0.4183.121-1.1
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7' 
      addToPath: true 
      architecture: 'x64'
  - powershell: pip install pypiwin32 
  - powershell: py build.py
  - powershell: py package.py
