# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Lightsail' 
  vmImage: 'windows-latest'

jobs:
- job: ungcBuild
  timeoutInMinutes: 360
  steps:
  - checkout: self
    submodules: true
  - powershell: git checkout --recurse-submodules 85.0.4183.121-1.1    
  - powershell: py build.py
    timeoutInMinutes: 360
  - powershell: py package.py
